### ISSUE TITLE
Provide ARM64 images

### ISSUE THREAD

**Issue by Kidswiss** [vshn/antora-preview#17]
Currently it's a pain to use `make preview` in the docs repos on an Apple Silicon Mac.

Although docker can be run through rosetta, it's very unstable and unreliable. The only option is to use qemu emulation which is slow. Most docs take over 1minute to build this way.

**Comment by arska** [comment]
I added multi-arch builds and on my Apple M1 Mac the "platform mismatch" error message is gone. The time from file save to browser refresh is now ~45s:
19:03:29 - INFO - Got change for: ...
19:04:15 - INFO - Reloading browser: ...
