### ISSUE TITLE
Configurable location for custom UI assets

### ISSUE THREAD

**Issue by rorokaloom** [vshn/antora-preview#3]
I have a `build` directory within my Antora project's home, would it be possible to specify the location of both the UI bundle (zip file) and supplemental-ui folder at container start. 

./build/ui-bundle.zip
./build/supplemental-ui

Using FF 80.0.1 (64-bit). Ubuntu 18.04 LTS app under WSL with Docker Desktop.

**Comment by akosma** [comment]
This feature is available as of version 2.3.6. Please refer to the README for information about how to use it (it basically revolves around adding a new `--volume` parameter to your `docker run` call).
