### ISSUE TITLE
Cannot find Antora file '/preview/antora/docs/antora.yml'

### ISSUE THREAD

**Issue by LarryEitel** [vshn/antora-preview#4]
Running:

`docker run --rm --publish 35729:35729 --publish 2020:2020 --volume "${PWD}":/preview/antora vshn/antora-preview:2.3.4 --antora=docs --style=appuio`

It returns:

`Cannot find Antora file '/preview/antora/docs/antora.yml'`

**Comment by akosma** [comment]
Make sure the `--antora` parameter points to the location of your `antora.yml` file. The location that appears on the error message is inside of the container, and is not a path in your own file system.

Also, in general, you might want to run this command on the root of the project containing the Antora documentation (that is, the parent dir of the `docs` folder of your project.)
